list: $/beysong/wechat/models/wechatmenu/columns.yaml
modelClass: Beysong\Wechat\Models\WechatMenu
title: WechatMenu
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'beysong/wechat/wechatmenu/update/:id'
