list: $/beysong/wechat/models/wechatuser/columns.yaml
modelClass: Beysong\Wechat\Models\WechatUser
title: OauthUser
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
